languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "https://shingohry.github.io/hugo-sample"
canonifyurls = true
title = "Pixyll"
author = "admin"
theme = "hugo-theme-pixyll"
disqusShortname = "sitename"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  # search_engine = true
  # google_analytics_id = "XX-XXXXXXXX-X"
  # twitter_username = "username"
  paginate = true
